// Most of these are AI generated

export const FACTS = [
    "The Apollo 11 guidance computer had less processing power than a modern calculator — yet it landed humans on the moon",
    "The first computer bug was an actual moth stuck in a Harvard Mark II relay in 1947",
    "The JPEG image format uses Discrete Cosine Transform (DCT), the same technique used in audio compression like MP3",
    "The first ransomware attack was in 1989 — it was distributed via floppy disks and demanded payment by mail",
    "Git was created by Linus Torvalds in just two weeks after a fight with a proprietary version control system",
    "Modern CPUs predict your next instructions using machine learning for better performance",
    "Most ATM machines run on Windows — some even still run on Windows XP",
    "Programming languages like Python and JavaScript were named after Monty Python and a café menu item, not snakes or Java",
    "Apple's first logo featured Isaac Newton sitting under a tree — not the iconic bitten apple",
    "The first webcam was used at Cambridge University to monitor a coffee pot",
    "Linux powers over 90% of the world's supercomputers — and your Android phone",
    "In 1995, Pixar had to recreate part of *Toy Story 2* after someone accidentally deleted it — backups failed, but one employee had a copy at home",
    "Typing 'why' into ChatGPT uses more electricity than boiling a kettle — thanks to the massive data centers behind the scenes",
    "CAPTCHAs were originally created not just for security but also to help digitize old books",
    "Quantum computers don't replace classical computers — they're more like specialized tools for ultra-hard problems",
    "Computer programming was once considered 'women's work' — the earliest programmers were women like Ada Lovelace and the ENIAC team",
    "Google's first storage system was built using LEGO bricks to house 10 x 4GB hard drives",
    "The first email ever sent was by Ray Tomlinson to himself in 1971 — and he doesn't remember what it said",
    "The QWERTY keyboard layout was designed to slow down typists to prevent typewriter jams",
    "The term 'bug' for computer errors became popular after the moth incident, but it was used as early as Thomas Edison's time",
    "Ctrl+Alt+Del was originally meant as a shortcut for rebooting IBM PCs during development — not for Task Manager",
    "SpaceX uses Linux to control rockets — the Falcon 9 runs on dual-core x86 processors and triple redundancy",
    "The average car today contains over 100 million lines of code — more than the Space Shuttle",
    "Facebook's 'Like' button was almost called the 'Awesome' button",
    "Bitcoin's creator, Satoshi Nakamoto, remains anonymous to this day — no one knows if it's one person or a group",
    "Minecraft was originally created in just six days by Markus Persson in 2009",
    "The term 'robot' comes from a Czech word 'robota', meaning forced labor",
    "In 1988, a 23-year-old student released one of the first internet worms — it infected ~10% of the internet in a day",
    "Unicode includes emojis, ancient scripts, and even Klingon — there are over 140,000 characters and counting",
];
